name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Ensure setup-python works with "act"
      run: |
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi  
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'  
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Type check with mypy
      run: |
        find .
        mypy --config-file setup.cfg steinbit tests
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with pytest
      run: |
        pytest --doctest-modules --junitxml=junit/test-results.xml
    - name: Build
      run: |
        python setup.py sdist bdist_wheel    
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: junit/test-results.xml
      if: ${{ always() }}
